options:
  scaleio-apt-repo:
    type: string
    default: "http://ec2-52-37-140-129.us-west-2.compute.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleOI packages.
