options:
  port:
    type: int
    default: 4443
    description: Port where gateway will listen.
  scaleio-packages-url:
    type: string
    default: "ftp://QNzgdxXix:Aw3wFAwAq3@ftp.emc.com/Ubuntu/2.0.12000.122"
    description: |
      URL of ScaleIO packages where charm can find them in appropriate structure.
  vip:
    type: string
    default:
    description: |
      Virtual IP to use to front API service in HA configuration.
      Only one IP is allowed. It will be passed to clients like
      OpenStack for accessing ScaleIO cluster.
      Haproxy will be installed and configured if vip is set.
  haproxy-server-timeout:
    type: int
    default:
    description: |
       Server timeout configuration in ms for haproxy, used in HA
       configurations. If not provided, default value of 30000ms is used.
  haproxy-client-timeout:
    type: int
    default:
    description: |
       Client timeout configuration in ms for haproxy, used in HA
       configurations. If not provided, default value of 30000ms is used.
  haproxy-queue-timeout:
    type: int
    default:
    description: |
       Queue timeout configuration in ms for haproxy, used in HA
       configurations. If not provided, default value of 5000ms is used.
  haproxy-connect-timeout:
    type: int
    default:
    description: |
       Connect timeout configuration in ms for haproxy, used in HA
       configurations. If not provided, default value of 5000ms is used.
