options:
  password:
    type: string
    default: "Default_password"
    description: "MDM password"
  scaleio-apt-repo:
    type: string
    default: "http://ec2-52-37-140-129.us-west-2.compute.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleIO packages.
