options:
  scaleio-apt-repo:
    type: string
    default: "http://scaleio-packages.s3-website-us-east-1.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleIO packages.
  scaleio-driver-ftp:
    type: string
    default: "ftp://QNzgdxXix:Aw3wFAwAq3@ftp.emc.com"
    description: |
      URL for driver_sync.sh script from sdc package to sync & verify driver.
