options:
  protection-domain:
    type: string
    default: "default_protection_domain"
    description: "Protection domain name"
  fault-set:
    type: string
    default: ""
    description: "Fault set name"
  storage-pools:
    type: string
    default: "default_storage_pool"
    description: "Comma-separated list of storage pool names"
  device-paths:
    type: string
    default: "/dev/sdb"
    description: "Comma-separated list of device paths"
  rfcache-device-paths:
    type: string
    default: ""
    description: "Comma-separated list of device paths for RF Cache"
  zero-padding-policy:
    type: string
    default:
    description: |
      Ensures that every read from an area previously not written to returns zeros.
      Some applications might depend on this behavior. Furthermore, zero padding
      ensures that reading from a volume will not return information that was
      previously deleted from the volume.
      Can be 'enable' or 'disable'.
  checksum-mode:
    type: string
    default:
    description: |
      This feature addresses errors that change the payload during the transit through the ScaleIO system.
      'enable' or 'disable'
  rmcache-usage:
    type: string
    default:
    description: |
      Server RAM that is reserved for caching storage devices in a Storage Pool.
      'use' or 'dont_use'
  rmcache-write-handling-mode:
    type: string
    default:
    description: |
      The caching write-mode used by the system: passthrough mode (writes to storage only),
      or cached mode (by default, writes both to cache and to storage).
      'cached' or 'passthrough'
  scanner-mode:
    type: string
    default:
    description: |
      The Background Device Scanner ("scanner") enhances the resilience of your ScaleIO system
      by constantly searching for, and fixing, device errors before they can affect your system.
      Can be 'enable' that means 'device_only' mode or 'disable'.
  spare-percentage:
    type: int
    default:
    description: |
      The number represents the percentage of total capacity set aside to ensure data integrity during server failures.
      The percentage is derived by 1/(number of SDS), which yields the recommended percentage for less than 10 balanced servers.
      For more information, see “Modifying spare policy” in the EMC ScaleIO User Guide.
  internal-iface:
    type: string
    default:
    description: |
      Interface to use for SDS-MDM and SDS-SDS communicaton.
      By default Juju will automatically determine internal IPs.
  storage-iface:
    type: string
    default:
    description: |
      Interface to use for SDS-SDC communicaton.
  scaleio-apt-repo:
    type: string
    default: "http://ec2-52-37-140-129.us-west-2.compute.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleIO packages.
  scaleio-driver-ftp:
    type: string
    default: "ftp://QNzgdxXix:Aw3wFAwAq3@ftp.emc.com"
    description: |
      URL for driver_sync.sh script from sdc package to sync & verify driver.
