options:
  protection-domain:
    type: string
    default: "default_protection_domain"
    description: "Protection domain name"
  fault-set:
    type: string
    default: ""
    description: "Fault set name"
  storage-pools:
    type: string
    default: "default_storage_pool"
    description: "Comma-separated list of storage pool names"
  device-paths:
    type: string
    default: "/dev/sdb"
    description: "Comma-separated list of device paths"
  zero-padding-policy:
    type: string
    default:
    description: |
      Ensures that every read from an area previously not written to returns zeros.
      Some applications might depend on this behavior. Furthermore, zero padding
      ensures that reading from a volume will not return information that was
      previously deleted from the volume.
      Can be 'enable' or 'disable'.
  internal-iface:
    type: string
    default:
    description: |
      Interface to use for SDS-MDM and SDS-SDS communicaton.
      By default Juju will automatically determine internal IPs.
  storage-iface:
    type: string
    default:
    description: |
      Interface to use for SDS-SDC communicaton.
  scaleio-apt-repo:
    type: string
    default: "http://ec2-52-37-140-129.us-west-2.compute.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleIO packages.
