options:
  password:
    type: string
    default: "Default_password"
    description: "MDM password"
  cluster-mode:
    type: int
    default: 1
    description: "Cluster mode. Valid values: 1,3,5"
  mgmt-iface:
    type: string
    default: eth0
    description: "Interface to use when determining MDM IP Address"
