options:
  password:
    type: string
    default: "Default_password"
    description: "MDM password"
  cluster-mode:
    type: int
    default: 1
    description: "Cluster mode. Valid values: 1,3,5"
  internal-iface:
    type: string
    default:
    description: |
      Interface used for MDM control communications with SDSs and
      SDCs, used to convey data migration decisions, but no user data passes
      through the MDM. Must be on the same network as the data network.
      Must be externally accessible if no MDM Management interface is used.
      By default Juju will automatically determine internal IPs.
  management-iface:
    type: string
    default:
    description: |
      Optional, but recommended;
      Interface that can be used to provide access to ScaleIO
      management applications, such as CLI, GUI, REST API,
      OpenStack. IP address of this interface must be externally accessible.
  scaleio-apt-repo:
    type: string
    default: "http://ec2-52-37-140-129.us-west-2.compute.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleIO packages.
  performance-profile:
    type: string
    default: high_performance
    description: |
      Performance profile for SDC/SDS. Can be default or high_performance.
  restricted-sdc-mode:
    type: string
    default:
    description: "Restricted SDC mode: 'enabled' or 'disabled'."
  license-file-path:
    type: string
    default:
    description: "Path to license file."
  remote-readonly-limit-state:
    type: string
    default:
    description: "Remote readonly limit state: 'enabled' or 'disabled'."
